//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.SGI.Propiedades {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Fabrica_Propiedades : global::System.Configuration.ApplicationSettingsBase {
        
        private static Fabrica_Propiedades defaultInstance = ((Fabrica_Propiedades)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Fabrica_Propiedades())));
        
        public static Fabrica_Propiedades Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ETNA.SGI.Data.FabricaDAO.FabricaDAOSQL")]
        public string Fabrica {
            get {
                return ((string)(this["Fabrica"]));
            }
        }
    }
}
